config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get 'colors/new_1' => 'colors#new_1'
  get 'colors/new_2' => 'colors#new_2'
  get 'colors/new_3' => 'colors#new_3'
  get 'colors/new_4' => 'colors#new_4'
  get 'colors/new_5' => 'colors#new_5'
  get 'colors/new_6' => 'colors#new_6'
  get 'colors/new_7' => 'colors#new_7'

  get 'colors/show_1' => 'colors#show_1'
  get 'colors/show_2' => 'colors#show_2'
  get 'colors/show_3' => 'colors#show_3'
  get 'colors/show_4' => 'colors#show_4'

  get 'colors/cloth_1' => 'colors#cloth_1'
  get 'colors/cloth_2' => 'colors#cloth_2'
  get 'colors/cloth_3' => 'colors#cloth_3'
  get 'colors/cloth_4' => 'colors#cloth_4'

  get 'shapes/new_1' => 'shapes#new_1'
  get 'shapes/new_2' => 'shapes#new_2'
  get 'shapes/new_3' => 'shapes#new_3'
  get 'shapes/new_4' => 'shapes#new_4'
  get 'shapes/new_5' => 'shapes#new_5'
  get 'shapes/new_6' => 'shapes#new_6'

  get 'shapes/show_1' => 'shapes#show_1'
  get 'shapes/show_2' => 'shapes#show_2'
  get 'shapes/show_3' => 'shapes#show_3'

  get 'shapes/cloth_1' => 'shapes#cloth_1'
  get 'shapes/cloth_2' => 'shapes#cloth_2'
  get 'shapes/cloth_3' => 'shapes#cloth_3'

  get 'tops/top' => 'tops#top'
  
  
  resources :shapes
  resources :colors
  root 'tops#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
end

app/models/shape.rb
class Shape < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  def index
  end



  def new_1
  end

  def new_2
  end

  def new_3
  end

  def new_4
  end

  def new_5
  end

  def new_6
  end

  def new_7
  end

  def show_1
  end

  def show_2
  end

  def show_3
  end

  def show_4
  end


end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
    def index
    end
  
    def new
      @shape = Shape.new
    end
  
    def show
      @shape = Shape.find_by(id: params[:id])
    end
  
    def create
      @shape = Shape.new(shape_params)
      params[:shape][:question] ? @shape.question = params[:shape][:question].join("") : false
      if @shape.save
          flash[:notice] = "診断が完了しました"
          redirect_to perfume_path(@shape.id)
      else
          redirect_to :action => "new"
      end
    end
  
  private
    def shape_params
        params.require(:perfume).permit(:id, question: [])
    end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController

 def top
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/colors/cloth_1.html.erb
<%=image_tag 'yellowtop.png',class:'yellowtop'%>
<div class="iebeharu">
       <div class="shindankekka">
          <h3>診 断 結 果<h3>
       </div>

       <%=image_tag 'haruhukunew.png',class:'haruhuku'%>

       <div class="haruosusumekode">
           <h4><span>おすすめコーデ</span><h4>
       </div>

       <%=image_tag 'yellowhukidashi.png',class:'yellowhukidashi'%>

       <div class="harutaipu">
           Spring type<br>
        </div>

        <div class="besu">
           <h5>イエローベース<h5>
        </div><br><br><br>

        <%=image_tag 'broline.png',class:'broline'%><br>

        <div class="haruniauhukuoomoji">
           <h4>似合う服の特徴<h4><br>
         </div>

         <div class="haruniauhukukomoji">
           <h5>イエベ春の人には、<span>フレッシュで可愛らしいテイストの服</span>がよく似合うよ！ふんわりとしたシルエ<br>ットのブラウスやスカートのほか、ボーダーやチェックなどの柄物もおすすめ。<br><br>
           赤や青などはっきりとした色の物ではなくて、<span>パステルカラーやアイボリー</span>を取り入れるのが◎<br>
           スプリング色を綺麗に発色させるためには、トップスの下には必ず<span>白の下着</span>を。
           苦手は<span>黒色</span>で、<br>コーデにはなるべく多く持ち込まないようにしよう。<br><br>
           その他、イエベ春の人は、<span>寒色系やくすみカラー</span>などが苦手な傾向。<br>
           コーディネートの主役にすると、表情を暗く見せてせっかくの元気なイメージを損ねてしまう可能<br>性があるため、控えよう。<br>
           そのようなカラーを取り入れる場合は、<span>バッグやシューズなどの小物</span>で取り入れるのがおすすめ。<h5><br>
         </div>

         <%=image_tag 'broline.png',class:'broline'%><br>

         <div class="haruniauhukuoomoji">
           <h4>おすすめコーデ<h4>
         </div>

         <div class="haruhukuphoto">
            <%=image_tag 'haruhuku1.png',class:'haruhuku1'%>
            <%=image_tag 'haruhuku2.png',class:'haruhuku2'%>
            <%=image_tag 'haruhuku3.png',class:'haruhuku3'%>
         </div>

        <div class="haruhukunametop">
         <div class="haruhukuname1">
           <h3>アイボリー<br>×<br>キャメル<h3>
         </div>
     
         <div class="haruhukuname2">
           <h3>パステルピンク<br>×<br>アイボリー<h3>
         </div>
     
         <div class="haruhukuname3">
           <h3>ライトオレンジ<br>×<br>アイスグリーン<h3>
         </div>
        </div>

        <br><br>
        <div class="haruhukuphoto">
        <%=image_tag 'haruhuku4.png',class:'haruhuku4'%>
        <%=image_tag 'haruhuku5.png',class:'haruhuku5'%>
        <%=image_tag 'haruhuku6.png',class:'haruhuku6'%>
     </div>

        <div class="haruhukunamesita">
         <div class="haruhukuname4">
           <h3>イエローグリーン<br>×<br>アイボリー<h3>
         </div>
     
         <div class="haruhukuname5">
           <h3>ホワイト<br>×<br>ブライトイエロー<h3>
         </div>
     
         <div class="haruhukuname6">
           <h3>パステルイエロー<br>×<br>パステルブルー<h3>
         </div>
        </div>

        <br>
        <br>
        <br>
        <br>
        <div class="tokutyonimodoru">
           <%= link_to "特徴に戻る", colors_show_1_path %>
        </div>
        <br>
        <br>
        <div class="rinkmatome">
             <div class="kokkakusindannhakotirakara">
                 <%= link_to "骨格診断はこちら", shapes_path %>
             </div>
             <br>
               <div class="mouitido">
                  <%= link_to "もう一度診断する", colors_path %>
               </div>
        
              <div class="homepagehe">
                  <%= link_to "ホームページに戻る", tops_top_path %>
              </div>
        </div>
        <br><br><br>

app/views/colors/cloth_2.html.erb
<%=image_tag 'burunatutop.png',class:'burunatutop'%>


<div class="burushindankekka">
          <h3>診 断 結 果<h3>
</div>

<%=image_tag 'natuhukunew.png',class:'natuhuku'%>

<div class="natuosusumekode">
           <h4><span>おすすめコーデ</span><h4>
</div>

<%=image_tag 'aohukidasi.png',class:'aohukidasi'%>

<div class="burutaipu">
           Summer type<br>
</div>

<div class="burubesu">
           <h5>ブルーベース<h5>
</div><br><br><br>

        <%=image_tag 'broline.png',class:'broline'%><br>

        <div class="natuniauhukuoomoji">
           <h4>似合う服の特徴<h4><br>
         </div>

         <div class="natuniauhukukomoji">
           <h5>ブルべ夏の人は、<span>爽やかで淡く柔らかい色</span>を選び、<span>ノンコントラスト</span>にするのがポイント。<br><br>
           明るさ・色・濃さ、何れにおいても強い差を付けずに、<span>穏やかな配色</span>をすることが肝心で、明るい<br>色には明るめ、暗い色には暗め、薄い色には薄め、濃い色には濃いめの色を合わせることで落ち着<br>くよ！<br><br>
           特に似合うのが<span>ブルー系の色</span>で、ブルーといっても<span>パステル系や少しくすんだトーンの色</span>が肌色に<br>マッチ！
           同じブルべでも、コントラストの強い色が似合う冬タイプの人とは真逆になるよ。<h5><br>
         </div>

         <%=image_tag 'broline.png',class:'broline'%><br>

         <div class="natuniauhukuoomoji">
           <h4>おすすめコーデ<h4>
         </div>

         <div class="natuhukuphoto">
            <%=image_tag 'natuhuku1.png',class:'natuhuku1'%>
            <%=image_tag 'natuhuku2.png',class:'natuhuku2'%>
            <%=image_tag 'natuhuku3.png',class:'natuhuku3'%>
         </div>

        <div class="natuhukunametop">
         <div class="natuhukuname1">
           <h3>くすんだブルー<br>×<br>オフホワイト<h3>
         </div>
     
         <div class="natuhukuname2">
           <h3>ラベンダー<br>×<br>ピンク<h3>
         </div>
     
         <div class="natuhukuname3">
           <h3>ダスティーブルー<br>×<br>ダスティーブルー<h3>
         </div>
        </div>

        <br><br>
        <div class="natuhukuphoto">
        <%=image_tag 'natuhuku4.png',class:'natuhuku4'%>
        <%=image_tag 'natuhuku5.png',class:'natuhuku5'%>
        <%=image_tag 'natuhuku6.png',class:'natuhuku6'%>
     </div>

        <div class="natuhukunamesita">
         <div class="natuhukuname4">
           <h3>オフホワイト<br>×<br>パープル<h3>
         </div>
     
         <div class="natuhukuname5">
           <h3>グレー<br>×<br>オフホワイト<h3>
         </div>
     
         <div class="natuhukuname6">
           <h3>インディゴブルー<br>×<br>ライトブルー<h3>
         </div>
        </div>

        <br>
        <br>
        <br>
        <br>
        <div class="tokutyonimodoru">
           <%= link_to "特徴に戻る", colors_show_2_path %>
        </div>
        <br>
        <br>
        <div class="rinkmatome">
             <div class="kokkakusindannhakotirakara">
                 <%= link_to "骨格診断はこちら", shapes_path %>
             </div>
             <br>
               <div class="mouitido">
                  <%= link_to "もう一度診断する", colors_path %>
               </div>
        
              <div class="homepagehe">
                  <%= link_to "ホームページに戻る", tops_top_path %>
              </div>
        </div>
        <br><br><br>

app/views/colors/cloth_3.html.erb
<%=image_tag 'akitop.png',class:'akitop'%>


<div class="akishindankekka">
          <h3>診 断 結 果<h3>
</div>

<%=image_tag 'akihukunew.png',class:'akihuku'%>

<div class="akiosusumekode">
           <h4><span>おすすめコーデ</span><h4>
</div>

<%=image_tag 'akihukidasi.png',class:'akihukidasi'%>

<div class="akitaipu">
           Autumn type<br>
</div>

<div class="akibesu">
           <h5>イエローベース<h5>
</div><br><br><br><br>
        <%=image_tag 'broline.png',class:'broline'%><br>

        <div class="akiniauhukuoomoji">
           <h4>似合う服の特徴<h4><br>
         </div>

         <div class="akiniauhukukomoji">
           <h5>イエベ秋の人は、<span>こっくりとした深みのある色</span>が得意で、秋の紅葉や、熟した果実などを連想さ<br>せる<span>落ち着いたカラー</span>をファッションコーディネートに取り入れると、上品で落ち着いた雰囲気に<br>まとまるよ。<br>
           <br>
           大人女性らしいしっとりした上品さがあるので、柄物のワンピースをブラウン系のカーディガンと<br>合わせるなど、<span>クラシカルなファッション</span>がポイント。<br><br>
           イエベ秋の似合うコーデは幅広く、特にオールブラウンなど<span>深みのあるカラーのワントーンコー<br>デ</span>は、トレンド感のある着こなしになるよ◎
           <h5><br>
         </div>

         <%=image_tag 'broline.png',class:'broline'%><br>

         <div class="akiniauhukuoomoji">
           <h4>おすすめコーデ<h4>
         </div>

         <div class="akihukuphoto">
            <%=image_tag 'akihuku1.png',class:'akihuku1'%>
            <%=image_tag 'akihuku2.png',class:'akihuku2'%>
            <%=image_tag 'akihuku3.png',class:'akihuku3'%>
         </div>

        <div class="akihukunametop">
         <div class="akihukuname1">
           <h3>ブラウン<br>×<br>グレージュ<h3>
         </div>
     
         <div class="akihukuname2">
           <h3>サックスブルー<br>×<br>サックスブルー<h3>
         </div>
     
         <div class="akihukuname3">
           <h3>ブラウン<br>×<br>ピンクレッド<h3>
         </div>
        </div>

        <br><br>
        <div class="akihukuphoto">
        <%=image_tag 'akihuku4.png',class:'akihuku4'%>
        <%=image_tag 'akihuku5.png',class:'akihuku5'%>
        <%=image_tag 'akihuku6.png',class:'akihuku6'%>
     </div>

        <div class="akihukunamesita">
         <div class="akihukuname4">
           <h3>サーモンピンク<br>×<br>モスグリーン<h3>
         </div>
     
         <div class="akihukuname5">
           <h3>ベージュ<br>×<br>ボルドー<h3>
         </div>
     
         <div class="akihukuname6">
           <h3>ブラウン<br>×<br>ゴールド<h3>
         </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <div class="tokutyonimodoru">
           <%= link_to "特徴に戻る", colors_show_3_path %>
        </div>
        <br>
        <br>
        <div class="rinkmatome">
             <div class="kokkakusindannhakotirakara">
                 <%= link_to "骨格診断はこちら", shapes_path %>
             </div>
             <br>
               <div class="mouitido">
                  <%= link_to "もう一度診断する", colors_path %>
               </div>
        
              <div class="homepagehe">
                  <%= link_to "ホームページに戻る", tops_top_path %>
              </div>
        </div>
        <br><br><br>

app/views/colors/cloth_4.html.erb
<%=image_tag 'huyutop.png',class:'huyutop'%>


<div class="huyushindankekka">
          <h3>診 断 結 果<h3>
</div>

<%=image_tag 'huyuhuku.png',class:'huyuhuku'%>

<div class="huyuosusumekode">
           <h4><span>おすすめコーデ</span><h4>
</div>

<%=image_tag 'huyuhukidasi.png',class:'huyuhukidasi'%>

<div class="huyutaipu">
           Winter type<br>
</div>

<div class="huyubesu">
           <h5>ブルーベース<h5>
</div><br><br><br><br>
        <%=image_tag 'broline.png',class:'broline'%><br>

        <div class="huyuniauhukuoomoji">
           <h4>似合う服の特徴<h4><br>
         </div>

         <div class="huyuniauhukukomoji">
           <h5>ブルベ冬の人は、<span>「純色」と言われる濁りのない色味</span>や、<span>鮮やかな色、白や黒などの無彩色</span>も<br>得意！<br><br>
           <span>モノトーンカラー</span>をベースにコーディネートを考えたり、モノトーンコーディネートに<span>アクセント<br>として鮮やかな色</span>を取り入れるだけでも、引き締まってかっこよくオシャレさんに！<br><br>
           コーデポイントは<span>強いコントラスト</span>を作ること◎<br>
           作るコントラストは主に明度(明暗)・彩度(濃淡)で、<span>色がはっきりしているもの</span>を組み合わせると<br>失敗しないよ。
           <h5><br>
         </div>

         <%=image_tag 'broline.png',class:'broline'%><br>

         <div class="huyuniauhukuoomoji">
           <h4>おすすめコーデ<h4>
         </div>

         <div class="huyuhukuphoto">
            <%=image_tag 'huyuhuku1.png',class:'huyuhuku1'%>
            <%=image_tag 'huyuhuku2.png',class:'huyuhuku2'%>
            <%=image_tag 'huyuhuku3.png',class:'huyuhuku3'%>
         </div>

        <div class="huyuhukunametop">
         <div class="huyuhukuname1">
           <h3>ブラック<br>×<br>ホワイト<h3>
         </div>
     
         <div class="huyuhukuname2">
           <h3>パープル<br>×<br>ブラック<h3>
         </div>
     
         <div class="huyuhukuname3">
           <h3>ブラック<br>×<br>グリーン<h3>
         </div>
        </div>

        <br><br>
        <div class="huyuhukuphoto">
        <%=image_tag 'huyuhuku4.png',class:'huyuhuku4'%>
        <%=image_tag 'huyuhuku5.png',class:'huyuhuku5'%>
        <%=image_tag 'huyuhuku6.png',class:'huyuhuku6'%>
     </div>

        <div class="huyuhukunamesita">
         <div class="huyuhukuname4">
           <h3>ブラック<br>×<br>ピンク<h3>
         </div>
     
         <div class="huyuhukuname5">
           <h3>ホワイト<br>×<br>ブルー<h3>
         </div>
     
         <div class="huyuhukuname6">
           <h3>ホワイトブラック<br>×<br>パープル<h3>
         </div>
        </div>

        <br>
        <br>
        <br>
        <br>
        <div class="tokutyonimodoru">
           <%= link_to "特徴に戻る", colors_show_4_path %>
        </div>
        <br>
        <br>
        <div class="rinkmatome">
             <div class="kokkakusindannhakotirakara">
                 <%= link_to "骨格診断はこちら", shapes_path %>
             </div>
             <br>
               <div class="mouitido">
                  <%= link_to "もう一度診断する", colors_path %>
               </div>
        
              <div class="homepagehe">
                  <%= link_to "ホームページに戻る", tops_top_path %>
              </div>
        </div>
        <br><br><br>

app/views/colors/index.html.erb
<div class="colorpagetopback">
    <div class="colorpagetopnihongo">
           <h1>パーソナルカラー診断<h1>
    </div>

    <div class="colorpagetopmoji">
    <h1>Personal color diagnosis<h1>
    </div>
    <br>
    <div class="colortopharunatuakihuyu">
    <%=image_tag 'toppagespring.png',class:'colortoppagespring'%>
    <%=image_tag 'toppagesummer.png',class:'colortoppagesummer'%>
    <%=image_tag 'toppageautumn.png',class:'colortoppageautumn'%>
    <%=image_tag 'toppagewinter.png',class:'colortoppagewinter'%>
    </div>
    <br>
        <div class="colorsindanzumi">
         <h1>診断済みはこちら<h1>
        </div>

      <div class="colorshinhtlink">
        <div class="colorstart">
            <%= link_to "診断を始める", colors_new_1_path%>
        </div>

        <div class="harupagehe">
            <%= link_to "イエベ春", colors_show_1_path%>
        </div>
        <div class="natupagehe">
            <%= link_to "ブルべ夏", colors_show_2_path%>
        </div>
        <div class="akipagehe">
            <%= link_to "イエベ秋", colors_show_3_path%>
        </div>
        <div class="huyupagehe">
            <%= link_to "ブルべ冬", colors_show_4_path%>
        </div>
      </div>
        <br>
</div>

app/views/shapes/cloth_1.html.erb
<div class="sutobackground">
  <%=image_tag 'sutohuku.png',class:'sutohuku'%>
  <div class="sutoshindankekka">
          <h3>診 断 結 果<h3>
  </div>
  <div class="sutoosusumekode">
           <h4><span>おすすめコーデ</span><h4>
  </div>
  <%=image_tag 'sutohuki.png',class:'hukusutohuki'%>
  <div class="sutotaipu">
    Straight type
  </div>
  
  <div class="hukusutotoku">
           <h5>上重心でメリハリのある<br>体つきが特徴<h5>
  </div>
  <br>
  <br>
 <br>
  <%=image_tag 'kuro.png',class:'kuro'%><br>

         <div class="sutooomoji">
           <h4>似合う服の特徴<h4><br>
         </div>

         <div class="sutokomoji">
           <h5><span>ハリ・リッチ＆メリハリボディ</span>のストレートタイプの人は、<span>厚み＆きれいめ素材</span>が肌映り良く<br>
           馴染み、<span>シルエット</span>でスタイルアップ。
           <h5><br>
         </div>

     <%=image_tag 'kuro.png',class:'kuro'%><br>

        <div class="sutooomoji">
           <h4>ポイント1：Ｖネックはマスト！<h4><br>
        </div>

        <div class="sutokomoji">
        <h5>ストレートタイプは<span>上半身に重心</span>があり、<span>体が分厚く見えやすい</span>タイプ。<br>
        そのため<span>トップスをスッキリ</span>させて見せることが何よりも意識したいポイント！<br><br>
        Vネックやスクエアネック、シャツやカシュクールなど、<span>縦に開いたネックライン</span>で、ざっくりと<br>
        <span>胸元を開けること</span>で重心が下がり、トータルコーデの見栄えがグッと良くなるよ。<br><br>
        反対に、首が短いので<span>ハイネック</span>は避けた方がベター。<h5><br>
        </div>

        <%=image_tag 'kuro.png',class:'kuro'%><br>
         <div class="sutooomoji">
            <h4>ポイント2：シンプルコーデが映える<h4><br>
         </div>

          <div class="sutokomoji">
            <h5>ストレートタイプは<span>ボディラインがはっきりしている</span>からこそ、<span>シンプルなコーディネート</span>が<br>
            バッチリ◎<br><br>
            もともと<span>ボリュームがある体</span>なので、フレンチスリーブやパフスリーブ、フレアスカートなどを<br>
            着用してしまうと、さらにボリュームが出てしまい、<span>太って見えるのでNG！</span><br><br>
            半そで、長袖、ノースリーブ、タイトスカートやストレートパンツなど<span>シンプルなデザイン</span>の<br>ものを選ぼう。<h5><br>
          </div>

          <%=image_tag 'kuro.png',class:'kuro'%><br>
         <div class="sutooomoji">
            <h4>ポイント3 :ジャストサイズが吉<h4><br>
         </div>

          <div class="sutokomoji">
            <h5><span>体が分厚く見えやすい</span>ストレートは、シルエットが大きすぎるものを選ぶと<span>着ぶくれに悩まされて<br>しまうよ。</span><br><br>
            腰の位置が高めなため、<span>ボトムスもジャストウエスト</span>のものがおすすめ◎
            <h5><br>
          </div>

          <%=image_tag 'kuro.png',class:'kuro'%><br>
         <div class="sutooomoji">
            <h4>おすすめコーデ<h4>
         </div>

         <div class="sutohukuphoto">
         <%=image_tag 'sutohuku1.png',class:'sutohuku1'%>
         <%=image_tag 'sutohuku2.png',class:'sutohuku2'%>
         <%=image_tag 'sutohuku3.png',class:'sutohuku3'%>
      </div>

     <div class="sutohukunametop">
      <div class="sutohukuname1">
        <h3>ロング丈ジレ<br>×<br>センタープレスパンツ<h3>
      </div>
  
      <div class="sutohukuname2">
        <h3>テーラードコート<br>×<br>ロング丈<h3>
      </div>
  
      <div class="sutohukuname3">
        <h3>ボアショートベスト<br>×<br>ストレートパンツ<h3>
      </div>
     </div>

     <br><br>
     <div class="sutohukuphoto">
     <%=image_tag 'sutohuku4.png',class:'sutohuku4'%>
     <%=image_tag 'sutohuku5.png',class:'sutohuku5'%>
     <%=image_tag 'sutohuku6.png',class:'sutohuku6'%>
  </div>

     <div class="sutohukunamesita">
      <div class="sutohukuname4">
        <h3>ハーフジップスウェット<br>×<br>タイトスカート<h3>
      </div>
  
      <div class="sutohukuname5">
        <h3>落ち感素材ワンピース<br>×<br>ジャストウエスト<h3>
      </div>
  
      <div class="sutohukuname6">
        <h3>スキッパーニット<br>×<br>ストレートパンツ<h3>
      </div>
     </div>
     <br>
     <br>
     <br>
     <br>
     <div class="tokutyonimodoru">
           <%= link_to "特徴に戻る", shapes_show_1_path %>
     </div>
     <br>
     <br>
     <div class="honerinkmatome">
          <div class="colorhakotirakara">
              <%= link_to "パーソナルカラー診断はこちら", colors_path %>
          </div>
          <br>
            <div class="honemouitido">
               <%= link_to "もう一度診断する", shapes_path %>
            </div>
     
           <div class="honehomepagehe">
               <%= link_to "ホームページに戻る", tops_top_path %>
           </div>
     </div>
     <br><br><br>
     </div>

</div>

app/views/tops/top.html.erb
<!DOCTYPE html> 
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>CSSの練習</title>
    <link rel="stylesheet" type="text/css" href="stylesheets/index.css">
<body>
  <header>
   <header class="header-nav">
   <%=image_tag 'rogo.png',class:'rogo'%>
   <nav><%= link_to "骨格診断", shapes_path%></nav>
   <nav><%= link_to "パーソナルカラー診断", colors_path%></nav>
  </header>
  
<!--  コンテンツを一旦仮置きする  -->
<br><br><br><br>
    <div class="loopSlide">
        <%=image_tag 'kansei.png',class:'kansei'%> <%=image_tag 'kansei.png',class:'kansei'%>
    </div>
<div class="first-block">
    

    <div class="topmoji">
        <br><br><br><br>
        <div class="topkoko">
            <h1>骨格診断<h1>
        </div>

        <div class="topkakeru">
            <h1>×<h1>
        </div>

        <div class="toppasonaritisindan">
            <h1>パーソナルカラー診断<h1>
        </div>

        <div class="topde">
            <h1>で<h1>
        </div>

        <div class="topanatano">
            <h1>あなたの<h1>
        </div>

        <div class="topsuki">
        <h1>好き<h1>
        </div>

        <div class="topmitukaru">
        <h1>が見つかる！！<h1>
        </div>


    </div>

    <%=image_tag 'mmm.png',class:'mmm'%>

    <div class="topharunatuakihuyu">
    <%=image_tag 'toppagespring.png',class:'toppagespring'%>
    <%=image_tag 'toppagesummer.png',class:'toppagesummer'%>
    <%=image_tag 'toppageautumn.png',class:'toppageautumn'%>
    <%=image_tag 'toppagewinter.png',class:'toppagewinter'%>
    </div>
</div>

    <div class="toplinkmatome">
        <div class="toppageshapestart">
            <%= link_to "骨格診断を始める", shapes_path%>
        </div>

        <div class="toppagecolorstart">
            <%= link_to "パーソナルカラー診断を始める", colors_path%>
        </div>
    </div>

  <footer>	
    <small>© Copyright 2023 Moe Narita.</small>
  </footer>

</body>